### ISSUE TITLE
Passwords not encrypting due to uninterpreted \n escapes

### ISSUE THREAD

**Issue by ghost** [yast/yast-bootloader#277]
When you try to setup password protection grub2-mkpasswd-pbkdf2 reports: error: failure to read password. I assume this is because the -e switch is not passed to echo in encrypt() so the escapes can't be interpreted. However I do not know what will happen if you put a \n in the password since echo does not care if escapes are quoted or not, you need to use double backslashes.

~~Possible fix:~~
~~https://github.com/hlindg/yast-bootloader/commit/1a1a93f63403a39172c71ba47a10f4b7665e857f~~

Edit: I have not been able to test this and it may not look like the most elegant solution but it may work:
https://github.com/hlindg/yast-bootloader/commit/8cb9b00ecee301e8d356d21e55912761e0cb9869
Let echo interpret the backslashes instead of ruby using -e plus double backslashes.

**Comment by arvidjaar** [comment]
Does it fix http://bugzilla.suse.com/show_bug.cgi?id=951898?

**Comment by hlindg** [comment]
Not sure why it would have anything to do with fonts, did you post the right link?

**Comment by arvidjaar** [comment]
Sorry.
https://bugzilla.suse.com/show_bug.cgi?id=954519

**Comment by hlindg** [comment]
Probably, it's the message I was talking about.

`$ echo '1234\n1234' | LANG=C grub2-mkpasswd-pbkdf2` does not work
`$ echo -e '1234\n1234' | LANG=C grub2-mkpasswd-pbkdf2` does work

**Comment by jreidinger** [comment]
I worry it won't fix it as \n is expanded on ruby level not on shell one. So in fact it send 
```
'1234
1234'
```
Do you test your fix if it helps?

**Comment by hlindg** [comment]
I don't actually know ruby, I just saw the bug and it seemed obvious to me, but does indeed seem to be a different issue.

I found the following:

    ~$ cat test.rb
    print("1234\n1234")
    ~$ echo $(ruby test.rb) | LANG=C grub2-mkpasswd-pbkdf2 
    Enter password: 
    Reenter password: grub2-mkpasswd-pbkdf2: error: failure to read password.
    ~$ echo -e $(ruby test.rb) | LANG=C grub2-mkpasswd-pbkdf2
    Enter password: 
    Reenter password: grub2-mkpasswd-pbkdf2: error: failure to read password.
    ~$ ruby test.rb | LANG=C grub2-mkpasswd-pbkdf2
    Enter password: 
    Reenter password: 
    PBKDF2 hash of your password is grub.pbkdf2.sha512.10000.236073D55BA9AEDA5135EFAF0F9999BCC6BCC44EBDF1750449977700E47718AFCACC3F7763C5D8E7E37FE4476228A82D07CE83BAE397196A007A4E81AD1EBA1F.4B78C173A1236FF362583BC93034B59D048320C1C593DB87DBC472212CD1C92E628C1B87215A09E1C591A7D83472FFE720A69544914CAC6DBF866CECE4259D2D

**Comment by jreidinger** [comment]
@hlindg if you want to test it properly you have to use:

```
`echo "a\na" | LANG=C grub2-mkpasswd-pbkdf2`
```
which do echo to script. Just try it. For me it works, but if it doesn't work for you, then maybe something changed in ruby?

**Comment by hlindg** [comment]
Does not output anything.

**Comment by hlindg** [comment]
I am using ruby 2.1.2p95 (2014-05-08 revision 45877).

**Comment by jreidinger** [comment]
@hlindg my fault, it just produce string. Just prepend print before `\``

**Comment by hlindg** [comment]
@jreidinger ah, ok.

**Comment by dgdavid** [comment]
The issue mentioned has been probably fixed after start using [cheetah](https://github.com/openSUSE/cheetah/) to put the [password directly to stdin](https://github.com/yast/yast-bootloader/blob/master/src/lib/bootloader/grub2pwd.rb#L132).
