### ISSUE TITLE
UEFI: elilo Boot Menu missing

### ISSUE THREAD

**Issue by smithfarm** [yast/yast-bootloader#456]
Günther J. Niederwimmer reports in https://bugzilla.opensuse.org/show_bug.cgi?id=720202

On a UEFI Installation the BootMenu is missing it is not Possible to Boot Failsafe or XEN?

I mean the elilo.conf is broken created from YaST2

On a debian system I have a construct like this 

```
//
## Elilo only supports up to 16 image definitions, so some desired
## installer configurations are commented out.
chooser=textmenu
default=Linux26
delay=20
prompt

message=boot-screens/elilo_menu.msg
f1=boot-screens/general.msg
f2=boot-screens/params.msg

image=2.6/vmlinuz
    label=Linux26
    description="Linux 2.6 [VGA console]"
    initrd=2.6/initrd.gz
    root=/dev/ram
    append="ramdisk_size=4352 --"
    read-only

image=vmlinuz
    label=Linux
    description="Linux 2.4 [VGA console]"
    initrd=initrd.gz
    root=/dev/ram
    append="ramdisk_size=13616 --"
    read-only
.....

//
```

This is missing also on a SLES 11 installation, I can't boot failsafe on a broken configuration from YaST2.

Reproducible: Always

**Comment by dgdavid** [comment]
As part of my Github issues cleanup task, I'm going to close this one because it's related to an unsupported SLES version.

Thanks.
