### ISSUE TITLE
Support systemd-boot

### ISSUE THREAD

**Issue by romulasry** [yast/yast-bootloader#590]
Anyone else want this?

**Comment by jreidinger** [comment]
well, for us currently grub2 is sufficient bootloader for all use cases we have. Do you have specific usage in mind that justify to maintain additional bootloader backend?

**Comment by romulasry** [comment]
No not at the moment. Thanks for your response.

**Comment by kobliha** [comment]
@jreidinger I would say that as this is just another alternative and does not provide anything that we wouldn't have already (and still wanted), we should close this issue as NO_THANKS. Or do you want to proceed further and put it to JIRA?

@romulasry I hope you don't mind. Asking for this is perfectly fine and we appreciate such hints in general. Thanks.

**Comment by jreidinger** [comment]
@kobliha well, I would close it as no thanks unless there start to be good reason to supporting it.

**Comment by dgdavid** [comment]
So, let's close it until we have 

> good reason to supporting it.

Thanks a lot for the input, guys.
