### ISSUE TITLE
Does Not Support LUKS Encrypted Root Partition with GRUB 2

### ISSUE THREAD

**Issue by ghost** [yast/yast-bootloader#597]
This can be fixed by ensuring `GRUB_ENABLE_CRYPTODISK=y` is set in the file `/boot/grub2/grub.cfg`

**Comment by Nageki** [comment]
I ran into this problem in the lastest TUmbleweed installer full cd

**Comment by Nageki** [comment]
uhh also I had secureboot on

**Comment by jreidinger** [comment]
It should be set by https://github.com/yast/yast-bootloader/blob/master/src/lib/bootloader/grub2base.rb#L376

Please open bug report in bugzilla and attacg yast logs. Thanks

**Comment by jreidinger** [comment]
as it should be solved via bugzilla with logs, lets this one.
